import { BrowserWindow, app, Menu, shell } from 'electron';
import defaultMenu from 'electron-default-menu';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let mainWindow: BrowserWindow | null = null;

export const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 1080,
    width: 1920,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      webSecurity: false,
      contextIsolation: true,
      nodeIntegration: true,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

app.whenReady().then(() => {
  // Add custom menu item "Preferences"
  const menu = defaultMenu(app, shell);

  menu.push({
    label: 'Preferences',
    submenu: [
      {
        label: 'Templates',
        click: () => mainWindow?.webContents.send('openTemplateModal'),
      },
    ],
  });

  // Apply the menu
  Menu.setApplicationMenu(Menu.buildFromTemplate(menu));

  app.on('activate', () => {
    // On macOS, recreate the window if the app has no windows open
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

// Exit when all windows are closed (except macOS)
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});
